In [145]:
import pandas as pd
import numpy as np

import statsmodels.api as sm

from train import return_vif, calculate_r_squared, scale_data

In [146]:
path = '~/Downloads/train_set.csv'
data = pd.read_csv(path, sep='\t')
data.columns

Index(['ID', 'Log price (1 billion VND)', 'Log area (square meters)',
       'Bedrooms', 'WC', 'Parking', 'For rent', 'Infrastructure', 'Facade',
       'Number of floors', 'Log usable area (square meters)', 'Latitude',
       'Longitude', 'Cluster', 'Distance to center 0', 'Distance to center 1',
       'Distance to center 2', 'Distance to center 3', 'Distance to center 4'],
      dtype='object')

In [147]:
data  = scale_data(data)

In [148]:
data["Price"] = np.exp(data["Log price (1 billion VND)"])
data["Area"] = np.exp(data["Log area (square meters)"])
data["Usable Area"] = np.exp(data["Log usable area (square meters)"])
data.drop(columns="Log price (1 billion VND)", inplace=True)
data.drop(columns="Log area (square meters)", inplace=True)
data.drop(columns="Log usable area (square meters)", inplace=True)
# data.drop(columns=["ID",
#                     "Log price (1 billion VND)", 
#                     "Parking",
#                     "Log area (square meters)", 
#                     'Log usable area (square meters)',
#                     "WC",
#                     "Latitude", 
#                     "Longitude",  
#                     "Number of floors", 
#                     "Cluster",
#                     'Distance to center 0', 
#                     'Distance to center 1', 
#                     'Distance to center 2', 
#                     'Distance to center 3', 
#                     'Distance to center 4'
#                    ], inplace=True)

In [149]:
data.head()

         ID  Bedrooms        WC  ...     Price      Area  Usable Area
0  0.004437 -0.400485  0.082193  ...  0.588423  0.275586     0.821707
1  0.650695 -0.400485 -0.843826  ...  4.566665  0.528803     0.370746
2  0.910272  0.030096  0.082193  ...  0.464030  1.391436     0.770017
3 -1.520802 -0.831066 -0.843826  ...  0.877389  0.259272     0.186595
4 -0.640030 -0.831066 -0.843826  ...  0.904976  0.696010     0.456267

[5 rows x 19 columns]

In [150]:
X_train = data.drop("Price", axis=1)
y_train = data["Price"]

In [151]:
return_vif(X_train)

                Features         VIF
0                     ID     1.01449
1               Bedrooms     3.27904
2                     WC     3.35004
3                Parking     1.07006
4               For rent     1.04940
5         Infrastructure     1.01361
6                 Facade     1.04815
7       Number of floors     2.51753
8               Latitude  1288.26336
9              Longitude    50.24168
10               Cluster    59.95424
11  Distance to center 0  5547.69349
12  Distance to center 1  1058.26678
13  Distance to center 2     4.04206
14  Distance to center 3  5350.71842
15  Distance to center 4  1204.94824
16                  Area     2.00162
17           Usable Area     2.96066

In [152]:
X_train.corr()

                                ID  Bedrooms  ...      Area  Usable Area
ID                    1.000000e+00 -0.026392  ... -0.022206    -0.047003
Bedrooms             -2.639233e-02  1.000000  ...  0.221338     0.526053
WC                   -4.630701e-02  0.812025  ...  0.113239     0.426213
Parking              -2.176733e-02  0.045758  ... -0.031697     0.032620
For rent              1.341698e-02  0.157073  ...  0.087183     0.123752
Infrastructure       -4.171229e-03  0.010205  ... -0.006709     0.028767
Facade                3.550333e-07  0.038070  ...  0.105620     0.038415
Number of floors     -5.860650e-02  0.536207  ...  0.038149     0.550816
Latitude              1.216741e-02  0.073661  ... -0.156524    -0.037588
Longitude             2.173734e-02 -0.040623  ...  0.166201     0.044035
Cluster               5.411458e-04  0.083992  ... -0.125504    -0.026168
Distance to center 0 -1.440739e-02 -0.069454  ...  0.155160     0.037871
Distance to center 1  1.303573e-02  0.072052  ... -0.152954    -0.038371
Distance to center 2 -5.889019e-02 -0.030061  ... -0.058734    -0.024227
Distance to center 3 -1.224461e-02 -0.072103  ...  0.159825     0.038331
Distance to center 4  8.071695e-03  0.069213  ... -0.172449    -0.043262
Area                 -2.220625e-02  0.221338  ...  1.000000     0.548840
Usable Area          -4.700266e-02  0.526053  ...  0.548840     1.000000

[18 rows x 18 columns]

In [153]:
X_train = sm.add_constant(X_train)
ols = sm.OLS(y_train, X_train).fit()
print(ols.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.217
Model:                            OLS   Adj. R-squared:                  0.208
Method:                 Least Squares   F-statistic:                     23.54
Date:                Mon, 17 Jun 2024   Prob (F-statistic):           9.37e-69
Time:                        20:52:33   Log-Likelihood:                -3339.8
No. Observations:                1548   AIC:                             6718.
Df Residuals:                    1529   BIC:                             6819.
Df Model:                          18
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                    1.4081      0.063     22.504      0.000       1.285       1.531
ID                       0.0319      0.054      0.593      0.554      -0.074       0.138
Bedrooms                 0.2287      0.098      2.339      0.019       0.037       0.421
WC                       0.1579      0.098      1.609      0.108      -0.035       0.350
Parking                 -0.0102      0.055     -0.185      0.854      -0.119       0.098
For rent                 0.1094      0.055      1.995      0.046       0.002       0.217
Infrastructure          -0.1150      0.054     -2.135      0.033      -0.221      -0.009
Facade                   0.3826      0.055      6.970      0.000       0.275       0.490
Number of floors         0.4223      0.085      4.962      0.000       0.255       0.589
Latitude                 0.4410      1.921      0.230      0.818      -3.327       4.209
Longitude                1.0416      0.380      2.744      0.006       0.297       1.786
Cluster                  1.8539      0.415      4.467      0.000       1.040       2.668
Distance to center 0   -15.5268      3.989     -3.892      0.000     -23.352      -7.702
Distance to center 1    -7.7230      1.745     -4.427      0.000     -11.145      -4.301
Distance to center 2     0.0811      0.108      0.754      0.451      -0.130       0.292
Distance to center 3    16.6379      3.918      4.247      0.000       8.953      24.323
Distance to center 4     7.6906      1.861      4.132      0.000       4.040      11.341
Area                     0.2234      0.021     10.596      0.000       0.182       0.265
Usable Area             -0.0388      0.016     -2.485      0.013      -0.069      -0.008
==============================================================================
Omnibus:                      937.715   Durbin-Watson:                   1.846
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9786.592
Skew:                           2.705   Prob(JB):                         0.00
Kurtosis:                      14.066   Cond. No.                         697.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [154]:
r_squared = pd.DataFrame()
r_squared["columns"] = X_train.columns
r_squared["r2"] = [calculate_r_squared(df=X_train, column=column) for column in X_train.columns]
r_squared

/home/tan/miniconda3/envs/handsonds/lib/python3.11/site-packages/statsmodels/regression/linear_model.py:1781: RuntimeWarning: divide by zero encountered in double_scalars
  return 1 - self.ssr/self.centered_tss

                 columns        r2
0                  const      -inf
1                     ID  0.014387
2               Bedrooms  0.700427
3                     WC  0.702628
4                Parking  0.065480
5               For rent  0.047797
6         Infrastructure  0.013438
7                 Facade  0.049136
8       Number of floors  0.604536
9               Latitude  0.999224
10             Longitude  0.980120
11               Cluster  0.983370
12  Distance to center 0  0.999820
13  Distance to center 1  0.999059
14  Distance to center 2  0.752622
15  Distance to center 3  0.999813
16  Distance to center 4  0.999173
17                  Area  0.424991
18           Usable Area  0.628132

In [155]:
ols.rsquared_adj

0.20778000028919175